# Add to coin.py the function summary(), that shows on screen some of the information generated by the functions we already have.
import coin

p = float(input('Enter price: $'))
coin.summary(p, 80, 35)
